package ntml;

enum TokenType {
    PAREN_LEFT, PAREN_RIGHT, BRACE_LEFT, BRACE_RIGHT,
    BRACKET_LEFT, BRACKET_RIGHT, ANGLE_RIGHT, ANGLE_LEFT,

    DOUBLE_BRACKET_LEFT, DOUBLE_BRACKET_RIGHT, DOUBLE_PAREN_LEFT, DOUBLE_PAREN_RIGHT,

    PLUS, SEMICOLON, HASH, DOUBLE_HASH, TRIPLE_HASH, STAR,
    COLON, BANG, HYPHEN, UNDERSCORE, BACKSLASH, SLASH, PIPE_HYPHEN,
    DOUBLE_HYPHEN, DOUBLE_BACKSLASH,

    PIPE, DOUBLE_PIPE,

    STRING, MATH, CODE,

    DOUBLE_NEWLINE,
    EOF
}